### ISSUE TITLE
Syntax error column name key in SQLite

### ISSUE THREAD

**Issue by samal-rasmussen** [nene/sql-parser-cst#80]
This:
```
CREATE TABLE key_value (key TEXT PRIMARY KEY, value TEXT
```

Results in:
```
Syntax Error: Unexpected "key"
Was expecting to see: "CHECK", "CONSTRAINT", "FOREIGN", "PRIMARY", "UNIQUE", identifier, or whitespace
--> undefined:1:25
  |
1 | CREATE TABLE key_value (key TEXT PRIMARY KEY, value TEXT;
  |                         ^
```

**Comment by nene** [comment]
Thanks for reporting.

I used [this list of keywords](https://sqlite.org/lang_keywords.html) in SQLite documentation, assuming none of these can be used as normal identifiers (as the text on that page suggests), but apparently not all of them are actually reserved keywords.

**Comment by samal-rasmussen** [comment]
Yeah I did not look at anything at all before I just used key as a column name :D I didn't even know basic stuff like "A keyword in double-quotes is an identifier.". Thanks for linking to the keyword docs.

I was a bit surprised that a formatter would care about this, but of course the formatter uses a parser, which has more reason to care.

**Comment by ad-si** [comment]
Same with `column` …

**Comment by nene** [comment]
Looks like this issue is a quite a bit more complex than I had anticipated. Turns out that whether a keyword can be used as identifier depends a lot on the context where it's used. Looks like these keywords can be grouped to 3 categories:

#### Always reserved

Some keywords are always reserved and can never be used as identifiers. For example `SELECT` cannot even be used in `AS` alias:

```sql
SELECT foo AS select FROM tbl; -- parse error
```

#### Never reserved

Some keywords can always be used as identifiers because they only appear as keywords in parts of syntax where an identifier can never be. For example `KEY` only occurs as part of `PRIMARY KEY` or `FOREIGN KEY`.

#### Sometimes reserved

The trickiest cases are keywords that can be used as identifiers in some places, but not in others. For example `COLUMN`. One can write without problems:

```sql
CREATE TABLE column (column INT);
SELECT column FROM column;
```

However one can't use that keyword when adding or removing columns. These all produce syntax errors:

```sql
ALTER TABLE foo ADD COLUMN column;
ALTER TABLE foo ADD column;
ALTER TABLE foo DROP COLUMN column;
ALTER TABLE foo DROP column;
```

**Comment by nene** [comment]
I've fixed the problem with `KEY` and `COLUMN`.

But there are many other keywords and it's hard to make a quick fix for all of them. I'll need to go an analyze each one carefully to determine whether they are fully reserved or not. But that's one big boring task to do, which I don't really desire doing... :(

I'll leave this issue open for more reports in the future.

**Comment by nene** [comment]
ON second thought... I'm gonna close this and open a separate issue: #92
