### ISSUE TITLE
Parsing postgres scripts fails with when it contains `CREATE EXTENSION`

### ISSUE THREAD

**Issue by buttilda** [nene/sql-parser-cst#93]
To reproduce attempt formatting this:
```sql
CREATE EXTENSION IF NOT EXISTS pgcrypto;
```

You'll get the following error:
```
Syntax Error: Unexpected "EXTENSION"
Was expecting to see: "EXTERNAL", "FOREIGN", "FULLTEXT", "GLOBAL", "INDEX", "LOCAL", "MATERIALIZED", "OR", "RECURSIVE", "SEARCH", "SNAPSHOT", "SPATIAL", "TABLE", "TEMP", "TEMPORARY", "TRIGGER", "UNIQUE", "UNLOGGED", "VECTOR", "VIEW", "VIRTUAL", or whitespace
--> undefined:1:8
  |
1 | CREATE EXTENSION IF NOT EXISTS pgcrypto;
```

**Comment by nene** [comment]
Thanks for reporting. This happens simply because a large part of PostgreSQL is not yet implemented by the parser.

You can see a work-in-progress list of what is and isn't supported in here: #40

I've created a separate task for the `CREATE/ALTER/DROP EXTENSION` syntax support and will close this one.
